version: 1.0.{build}

image:
- Ubuntu2004
- Visual Studio 2022
- macos

init:
- sh: if [[ "$OSTYPE" == "linux-gnu"* ]]; then (sudo apt update && sudo apt install -y xorg-dev libpulse-dev) fi

build_script:
- sh: git submodule init && git submodule update && cmake . && make
- cmd: git submodule init && git submodule update && mkdir build && cd build/ && cmake .. && cmake --build .
